data:
  prices:
    path: C:\Users\robin\Documents\OroTitan_V1.4\oro_titan\data_proc\prices_eod.csv
backtest: null
start: 2023-11-15
end: 2024-02-29
signals:
  mom:
    lookback_days: 3
strategy:
  topN: 1
rebalance:
  days: 1
costs:
  bps: 5
