data:
  prices:
    path: C:\Users\robin\Documents\OroTitan_V1.4\oro_titan\data_proc\prices_eod.csv
backtest:
  start: '2024-03-28'
  end: '2024-04-12'
signals:
  mom:
    lookback_days: 10
strategy:
  topN: 2
rebalance:
  days: 1
costs:
  bps: 5
