grid:
  - signals.mom.lookback_days: [3, 5, 10, 20]
  - strategy.topN:             [1, 2]
  - rebalance.days:            [1, 5]

# (facultatif) bornes temporelles globales pour le sweep :
# backtest:
#   start: 2024-02-12
#   end:   2024-04-12
