data:
  prices:
    path: ../data_proc/prices_sample.csv
backtest:
  start: 2023-12-01
  end: 2024-01-31
signals:
  kind: mom
  mom:
    lookback_days: 3
strategy:
  topN: 1
  long_only: true
  require_positive_signal: true
  min_weight_change: 0.02
  hold_period_days: 2
rebalance:
  days: 1
costs:
  bps: 5
