name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-lock.txt
          pip install pytest

      - name: Run tests
        env:
          PYTHONPATH: src
        run: |
          pytest -q

      - name: Run v3 summarize (optional)
        shell: pwsh
        run: |
          powershell -File .\tools\summarize.ps1

      - name: Upload summary artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: v3-summary
          path: reports/_index_v3_plus.csv
          if-no-files-found: ignore
